schema_version = "1.0.0"

id = "io_import_rbsp"
name = "io_import_rbsp"
version = "1.3.0"
blender_version_min = "4.2.0"

type = "add-on"
tags = ["Import-Export"]

tagline = "Import maps from Titanfall, Titanfall 2 & Apex Legends"
maintainer = "Jared Ketterer (snake-biscuits / Bikkie)"
website = "https://github.com/snake-biscuits/io_import_rbsp"

license = ["SPDX:GPL-3.0"]
copyright = ["2021 Jared Ketterer"]

wheels = ["./wheels/bsp_tool-0.5.0-py3-none-any.whl"]

[permissions]
files = "Import .bsp files"
