schema_version = "1.0.0"

id = "io_import_rbsp"
version = "1.3.0"
name = "io_import_rbsp"
tagline = "Import maps from Titanfall, Titanfall 2 & Apex Legends"
maintainer = "Jared Ketterer (snake-biscuits / Bikkie)"
type = "add-on"

website = "https://github.com/snake-biscuits/io_import_rbsp"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0",
]
copyright = [
   "2021 Jared Ketterer",
]

wheels = [
  "./wheels/bsp_tool-0.5.0-py3-none-any.whl"
]

[permissions]
files = "Import .bsp files"

# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]